### ISSUE TITLE
How to draw circle and rectangle shapes ?

### ISSUE THREAD

**Issue by AbdunNurTomal** [omarhurani/flutter_painter#1]
Salam, i am using this package but want more shape to draw as like **circle, rectangle, arrow**. Your controller have only freeStyles and text. Please suggest me

**Comment by omarhurani** [comment]
Currently, it is not supported. For now, you can inherit the `ObjectDrawable` widget and implement your own shapes which can be rotated, scaled and translated across the painting canvas. However, I'll work on adding shapes as soon as possible.

**Comment by omarhurani** [comment]
A new version (0.2.x) of the package has been released, which adds official support for shapes.
