### ISSUE TITLE
Not working on lower version

### ISSUE THREAD

**Issue by dimple3695** [omarhurani/flutter_painter#10]
This plugin is not supported in without null safety.
Getting this error:
This error getting in ObjectWidget class. size parameters is not getting.
`  final newDrawable = drawable.copyWith(
      size: Size(
        vertical ? drawable.size.width : totalLength,
        vertical ? totalLength : drawable.size.height,
      ),
      position: initial.position + position,
      // scale: scale,
      // rotation: assistedRotation,
      // assists: assists,
    );`

**Comment by omarhurani** [comment]
Can you please provide `flutter doctor -v` logs?

**Comment by dimple3695** [comment]
Flutter version 1.22.5 
    • Framework revision 7891006299 (1 year ago)
    • Engine revision ae90085a84
    • Dart version 2.10.4

**Comment by omarhurani** [comment]
Flutter version 1.22.5 does not support Dart version 2.12.0. You'll have to use a version that supports it (2.0.0 and higher) to be able to use the package. You can keep using Flutter without sound null-safety even if you upgrade your Flutter SDK to a version that supports it.
