### ISSUE TITLE
Done button required in iOS

### ISSUE THREAD

**Issue by venkata-subbarao** [omarhurani/flutter_painter#11]
Hi,

Great package. For add text feature we need to tap outside keyboard to close the keyboard. It would be better to have done button.

Thanks,
Subbarao

**Comment by omarhurani** [comment]
The problem with this is that the **done** and **return** button take the same location, so if the button is switched to **done**, you wouldn't be able to add a new line.

**Comment by omarhurani** [comment]
Closed for inactivity.
