### ISSUE TITLE
Text renders new lines incorrectly

### ISSUE THREAD

**Issue by Szugalew** [omarhurani/flutter_painter#19]
I think I found a bug with the text. When you add text and write enough that it gets wrapped onto a new line it looks like image 1. However, when you render this, the text gets cut off and it looks like image 2. The screenshots are from the web example. Btw, thank you so much for making this package, I really like it.

<img width="1023" alt="Screen Shot 2022-02-07 at 8 40 02 PM" src="https://user-images.githubusercontent.com/44127527/152901694-793b2c9a-4b8f-4a42-986c-595c6e6b71b4.png">
<img width="925" alt="Screen Shot 2022-02-07 at 8 40 26 PM" src="https://user-images.githubusercontent.com/44127527/152901733-153f5053-625c-4feb-b9e1-69b013339979.png">

**Comment by omarhurani** [comment]
Fixed in version 1.0.1.
