### ISSUE TITLE
Go Back Swipe

### ISSUE THREAD

**Issue by apoleo88** [omarhurani/flutter_painter#24]
It appears to exist a bug for which is not possible to remove the swipe gesture to navigate back in flutter.

```
Flutter 2.10.3 • channel stable 
Dart 2.16.1
```

It is not possible to remove it disabling it completely with `WillPopScope` because even if it doesn't go back on the gesture it won't start drawing if it is been tapped on the left side. (from the right side too)

I wonder if anyone has already encountered the same problem and solved it somehow?

**Comment by omarhurani** [comment]
I'm not sure I understand what you're trying to do, can you please explain a bit more?

**Comment by apoleo88** [comment]
In Android API 32 (maybe from 31 ?) and in iOS there is a go-back gesture when you drag from left to right.

![Screenshot_1646669498](https://user-images.githubusercontent.com/7873856/157073082-6ea64e9a-7753-4b84-88fc-782270f55d18.png)

It appears a left arrow in the top left corner and it will pop the page.
There are right to left drags gestures too.

It interferes interrupting the draw.

I tried to disable it, like:
```
WillPopScope(
  onWillPop: () async => false,
  child: <children here>
)
```

But it still pops the arrow and it will interrupt the draws.

There is still an open issue of 4 years ago: [https://github.com/flutter/flutter/issues/14203](https://github.com/flutter/flutter/issues/14203)

Do you have any solutions?

**Comment by omarhurani** [comment]
I don't think I can do anything about that. Maybe add some padding around the painter to avoid the edges?
