### ISSUE TITLE
Shapes outside popupmenubutton

### ISSUE THREAD

**Issue by rafildo** [omarhurani/flutter_painter#26]
I would like to draw the shapers inside a container and not in a popupmenu. Would it be possible to do this, do you have an example?

Thanks

**Comment by omarhurani** [comment]
You mean the buttons for drawing? Of course you can, the PopupMenu is just to trigger this method:

https://github.com/omarhurani/flutter_painter/blob/8405829f6a33dd607e520b94f18ce817fcfcd262/example/lib/main.dart#L564-L566

You can implement the UI however you wish.

**Comment by rafildo** [comment]
I could understand now and add the controllers in a Row.

`Row(
            children: [
              IconButton(
                icon: Icon(
                  PhosphorIcons.line_segment,                
                ),
                onPressed: () async {
                  setShapeFactory(LineFactory());                },
              ),
              IconButton(
                icon: Icon(
                  PhosphorIcons.arrow_up_right,                 
                ),
                onPressed: () async {
                  setShapeFactory(ArrowFactory());
                },
              ),
],
),`

There's one thing I couldn't do. I'll open another issue to facilitate the search for other users.

Thanks! It's amazing!
