### ISSUE TITLE
Flutter web app can't save correctly on Flutter SDK 3.0.5 

### ISSUE THREAD

**Issue by scrtkr** [omarhurani/flutter_painter#38]
This save function works well on Flutter SDK 2.5.0
flutter build web 
background image was not saved.

final ui.Image renderedImage = await controller.renderImage(size);
final Uint8List? byteData = await renderedImage.pngBytes;

**Comment by Gamebielo** [comment]
https://stackoverflow.com/questions/73278802/flutter-web-save-ui-image-to-png-file
This resolution worked for me, but it only works in the release, after the build, while we are testing (debug) it doesn't work

**Comment by BytesZero** [comment]
[我确认这是 Flutter 的问题，](https://github.com/flutter/flutter/issues/94895)

**Comment by asif786ka** [comment]
Hi Resolution Team. Any progress on this issue?It is impacting our product on web in production. Any workaround for this?

**Comment by otmi100** [comment]
Had the same issue. When building with the master branch of flutter it works again, not on stable though.

**Comment by scrtkr** [comment]
flutter_painter:
    git:
      url: https://github.com/Sheikhsoft/flutter_painter
      ref: 134d49f3db332cf22c195bcb5783f94102ae9fbd #commit hash

// it fixed issue
