### ISSUE TITLE
Does the package have method or function to remove all drawables?

### ISSUE THREAD

**Issue by VietNguyen392** [omarhurani/flutter_painter#47]

**Comment by sandundev** [comment]
I ended up doing this. You can also call undo() while 'canUndo = true'.

  Future<void> undoAll() async {
    controller = PainterController(...);
    initBackground(backgroundImage!);
  }

**Comment by VietNguyen392** [comment]
> I ended up doing this. You can also call undo() while 'canUndo = true'.
> 
> Future undoAll() async { controller = PainterController(...); initBackground(backgroundImage!); }

litte late but thank for response
